name: cargo build

on:
  push:
    branches: ["main"]
    tags:
      - 'v*'
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: rust_hello_world

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: "-D warnings"

    - name: check formatting
      run: cargo fmt --check
    
    - name: run clippy
      run: cargo clippy --all-targets --all-features

    - name: build project
      run: cargo build --release

  release:
    name: Github Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset-suffix: linux.tar.gz
          - os: windows-latest
            asset-suffix: windows.zip

    runs-on: ${{matrix.os}}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain (release build)
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Compile release binary
        run: cargo build --release

      - name: Package linux binary asset
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd target/release
          tar -czf ../../$${{env.PROJECT_NAME}}-${{github.ref_name}}-{{matrix.asset-suffix}} ${{env.PROJECT_NAME}}
          cd ../..

      - name: Package windows binary asset
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path target\release\${{env.PROJECT_NAME}}.exe -Destination ${{env.PROJECT_NAME}}-${{github.ref_name}}-${{matrix.assert-suffix}}

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.ref_name}}
          generate_release_notes: true
          files: ${{env.PROJECT_NAME}}-${{github.ref_name}}-${{matrix.assert-suffix}}


